EXE =
LIB = libboard.a 

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/kernel/core/inc \
    $(ROOT)/code/platform/kernel/arch/$(ARCH)/$(CPU)/inc \
    $(ROOT)/code/platform/kernel/device/inc \
    $(ROOT)/code/platform/kernel/driver/ctrlc/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
