EXE = 
LIB = 

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/kernel/arch/$(ARCH)/$(CPU)/inc \
    $(ROOT)/code/platform/kernel/core/inc \

LINK_LIBS = core board ctrlc cpu arch common

include $(BUILD)/c.rule
