EXE = 
LIB = libcore.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/kernel/arch/$(ARCH)/$(CPU)/inc \
    $(ROOT)/code/platform/kernel/core/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
