EXE = 
LIB = libctrlc.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/kernel/core/inc \
    $(ROOT)/code/platform/kernel/arch/x86/simulator/inc \
    $(ROOT)/code/platform/kernel/driver/console/inc \
    $(ROOT)/code/platform/kernel/driver/ctrlc/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
